export const bankData = [
    {
        id: 1,
        accountName: "กองทุนช่วยเหลือ",
        accountNumber: "202500001",
        openDate: "23/04/2025",
        accountType: "บัญชีออมทรัพย์",
        isActive: true,
        note: "เปิดเมื่อวันที่...ไว้สำหรับ...",
        accountFile: null,
    },
    {
        id: 2,
        accountName: "กองทุนช่วยเหลือ",
        accountNumber: "202500002",
        openDate: "23/05/2025",
        accountType: "บัญชีออมทรัพย์",
        isActive: false,
        note: "",
        accountFile: null,
    },
    {
        id: 3,
        accountName: "กองทุนช่วยเหลือ",
        accountNumber: "202500003",
        openDate: "23/06/2025",
        accountType: "บัญชีออมทรัพย์",
        isActive: true,
        note: "",
        accountFile: null,
    },
];